[package]
name = "rustacuda"
version = "0.1.0"
authors = ["Brook Heisler <brookheisler@gmail.com>"]

description = "CUDA Driver API Wrapper"
repository = "https://github.com/bheisler/rustacuda"
readme = "README.md"
license = "Apache-2.0/MIT"

[dependencies]
cuda-sys = "0.2"
bitflags = "1.0"

[dev-dependencies]
rustacuda_macros = { version = "0.1.0", path = "rustacuda_macros" }