[package]
name = "rustacuda"
version = "0.1.0"
authors = ["Brook Heisler <redattack34@gmail.com>"]

[dependencies]
cuda-sys = "0.2"

[dev-dependencies]
rustacuda_macros = { version = "0.1.0", path = "rustacuda_macros" }