[package]
name = "rustacuda_core"
version = "0.1.0"
authors = ["Brook Heisler <brookheisler@gmail.com>"]

description = "Minimal kernel-support crate for Rustacuda"
repository = "https://github.com/bheisler/RustaCUDA"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[dependencies]
