[package]
name = "rustacuda_macros"
version = "0.1.0"
authors = ["Brook Heisler <redattack34@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.15.18"
quote = "0.6.9"
proc-macro2 = "0.4.20"